"========================================================

" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" Vim theme
Plug 'altercation/vim-colors-solarized'

" A fancy start screen for vim
Plug 'mhinz/vim-startify'

" Underlines the word under the cursor
Plug 'itchyny/vim-cursorword'

" Lean & mean status/tabline for vim that's light as air
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

Plug 'yggdroot/indentline'

" Initialize plugin system
call plug#end()

"========================================================

set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8

syntax on
set background=dark
let g:solarized_termcolors=256
colorscheme solarized

inoremap jj <ESC>
set number
"set relativenumber 
set norelativenumber
set wrap
set showcmd
set wildmenu
set hlsearch


"map s <nop>  " s: 删除光标盖住的字符，进入插入模式
"map S :w<CR> " S: 删除光标所在行，进入插入模式
"map Q :q<CR> " Q: 还不清楚
"map R :source $MYVIMRC<CR> " R: 进入替换模式，直至ESC离开 

