syntax on
inoremap jj <ESC>
set number
"set relativenumber 
set norelativenumber
set wrap
set showcmd
set wildmenu
set hlsearch


"map s <nop>  " s: 删除光标盖住的字符，进入插入模式
"map S :w<CR> " S: 删除光标所在行，进入插入模式
"map Q :q<CR> " Q: 还不清楚
"map R :source $MYVIMRC<CR> " R: 进入替换模式，直至ESC离开 

"shen guibin
"Hello world!

